# -*- coding: utf-8 -*-
"""Credit_Card_Fraud_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ForyKIH7tDoAbHzJ10jV-cEo12banICJ

Importing the dependencies
"""

import numpy as np
import pandas as pd
import warnings
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings("ignore", category=ConvergenceWarning)

# Loading the dataset to a Pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

# First 5 rows of the dataset
credit_card_data.head()

# Last 5 rows of the dataset
credit_card_data.tail()

# Dataset Info
credit_card_data.info()

# Checking the number of missing values in each column
credit_card_data.isnull().sum()

# Distribution of legit and fraudulent transactions
credit_card_data['Class'].value_counts()

"""This dataset is highly unbalanced

Class 0 --> Normal/Legit Transaction

Class 1 --> Fraudulent Transaction
"""

# Seperating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

print(legit.shape)
print(fraud.shape)

# Statistical measures of the data
legit.Amount.describe()

fraud.Amount.describe()

# Compare the values for both the transactions
credit_card_data.groupby('Class').mean()

"""Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions

Number of fraudulent transactions --> 492
"""

legit_sample = legit.sample(n=492)

"""Concatenating two dataframes"""

new_dataset = pd.concat([legit_sample, fraud], axis=0)

new_dataset.head()

new_dataset.tail()

new_dataset['Class'].value_counts()

new_dataset.groupby('Class').mean()

"""Splitting the data into features and targets"""

X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

print(X)

print(Y)

"""Split the data into training data and testing data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

"""Model Training

Logistic Regression
"""

model = LogisticRegression()

# Training the Logistic Regression Model with training data
model.fit(X_train, Y_train)

"""Model Evaluation

Accuracy Score
"""

# Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy on training data:', training_data_accuracy)

# Accuracy on training data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy on testing data:', test_data_accuracy)